name: gh-on-issue

on:
  issues:
    types:
      - opened

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - uses: actions/checkout@v2

      - name: Create content
        run : |
          mkdir -p content/posts
          git clone https://github.com/spf13/hyde.git themes/hyde
          file="content/posts/${{ github.event.issue.number }}.md"

          touch $file
          echo "---" > $file
          echo "title: \"${{ github.event.issue.title }}\"" >> $file
          echo "date: 2021-11-14T22:40:38Z" >> $file
          echo "draft: false" >> $file
          echo "---" >> $file
          echo "" >> $file
          echo "${{ github.event.issue.body }}" >> $file

          hugo -D -b https://aryamanz29.github.io/posts/ -t hyde

      - name: Publish content
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: 'New content: ${{ github.event.issue.title }}'
          commit_options: '--allow-empty'
          repository: .
          status_options: '--untracked-files=no'
          file_pattern: 'content/**/*'
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: true
          disable_globbing: true

      - name: Update Gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public